#!/usr/bin/env bash

builtin set -xuo pipefail

# logging
TMPDIR="${TMPDIR:-/run/user/${UID:-$(id -u)}}"
LOG_DIR="$TMPDIR/waybar/WaybarThemes"
mkdir -p "$LOG_DIR"
exec 1> "$LOG_DIR/waybar.log"
exec 2>&1

NUM=${1:-1}
TOTAL_AVAILABLE_THEMES=0 FOUND_SWWW=0
CONFIG_DIR="$HOME/.config/niri"
THEME_DIR="${CONFIG_DIR}/waybar/themes"

function toggle_theme() {
    local action="${1:-"reload_current_theme"}"

    local current_waybar_style="${THEME_DIR}/current/style.css" \
        current_waybar_config="${THEME_DIR}/current/config.jsonc" msg=""

    if [[ "${action}" == "toggle_next"* ]]; then
        NUM=$(( (NUM % TOTAL_AVAILABLE_THEMES) + 1))
        msg="Started Waybar with profile: ${NUM}"
    elif [[ "${action}" == "reload_current"* ]]; then
        msg="Reloaded Waybar with current profile: $NUM"
    else
        msg="Nothing got selected"
    fi

    background_img="${THEME_DIR}/$NUM/bg/bg"

    if [[ "$FOUND_SWWW" -eq 1 ]]; then
        awww img "${background_img}" --transition-type fade --transition-duration 1
    else
        swaybg -o '*' -i "${background_img}" -m fill &>/dev/null &
    fi

    ln -sf ../$NUM/config.jsonc "${current_waybar_config}"
    ln -sf ../$NUM/style.css "${current_waybar_style}"

    if ! pgrep -f "waybar -c ${current_waybar_config} -s ${current_waybar_style}" &> /dev/null; then
        waybar -c "${current_waybar_config}" -s "${current_waybar_style}" &> /dev/null &
    fi

    sleep 0.2 && pkill -SIGUSR2 -f "waybar -c .* -s .*"

    notify-send -t 1000 "${msg}" || true
}

function main() {
    NUM=$((NUM-1))

    pgrep -f "bash .*${0}" | grep -v "^$$" | xargs -r kill &> /dev/null || true

    TOTAL_AVAILABLE_THEMES=$( \
        find "${THEME_DIR}"/[0-9] \
            -mindepth 0 -maxdepth 0 \
            -type d -printf '.' | wc -c \
    )

    if command -v "awww-daemon" &> /dev/null; then
        FOUND_SWWW=1; pkill -f '.*awww-daemon'; awww-daemon &>/dev/null & disown
    fi

    trap 'toggle_theme toggle_next_theme'     SIGUSR1
    trap 'toggle_theme reload_current_theme'  SIGUSR2
    trap 'kill $COPROC_PID; exit 0'           SIGINT SIGTERM

    toggle_theme toggle_next_theme

    coproc sleep inf
    # shellcheck disable=SC2034
    read -r line <&"${COPROC[0]}"
}

main "${@}"

