#!/usr/bin/env bash

set -uo pipefail
set -x

NUM=${1:-1}
TOTAL_AVAILABLE_THEMES=0 FOUND_SWWW=0
CONFIG_DIR="$HOME/.config/niri"
THEME_DIR="${CONFIG_DIR}/waybar/themes"

function toggle_theme() {
    local action="${1:-"reload_current_theme"}"

    local current_waybar_style="${THEME_DIR}/current/style.css" \
        current_waybar_config="${THEME_DIR}/current/config.jsonc" msg=""

    if [[ "${action}" == "toggle_next"* ]]; then
        NUM=$(( (NUM % TOTAL_AVAILABLE_THEMES) + 1))
        msg="Started Waybar with profile: ${NUM}"
    elif [[ "${action}" == "reload_current"* ]]; then
        NUM=${NUM}
        msg="Reloaded Waybar with current profile: $NUM"
    else
        msg="Nothing got selected"
    fi

    background_img="${THEME_DIR}/$NUM/bg/bg"

    if [[ "$FOUND_SWWW" -eq 1 ]]; then
        awww img "${background_img}" --transition-type fade --transition-duration 1
    else
        swaybg -o '*' -i "${background_img}" -m fill &>/dev/null &
    fi

    ln -sf ../$NUM/config.jsonc "${current_waybar_config}"
    ln -sf ../$NUM/style.css "${current_waybar_style}"

    if ! pgrep -f "waybar -c ${current_waybar_config} -s ${current_waybar_style}" &> /dev/null; then
        waybar -c "${current_waybar_config}" -s "${current_waybar_style}" &> /dev/null &
    fi

    sleep 0.2 && pkill -SIGUSR2 -f "waybar -c .* -s .*"

    notify-send -t 1000 "${msg}" || true
}

function main() {
    NUM=$((NUM-1))

    pgrep -f "bash .*${0}" | grep -v "^$$" | xargs -r kill &> /dev/null || true

    for i in "${THEME_DIR}"/[0-9]*; do
        TOTAL_AVAILABLE_THEMES=$((TOTAL_AVAILABLE_THEMES + 1))
    done

    if command -v "awww-daemon" &> /dev/null; then
        FOUND_SWWW=1; pkill -f '.*awww-daemon'; awww-daemon &>/dev/null & disown
    fi

    trap 'toggle_theme toggle_next_theme'     SIGUSR1
    trap 'toggle_theme reload_current_theme'  SIGUSR2
    trap 'exit 0'                             SIGINT SIGTERM

    toggle_theme toggle_next_theme

    while true; do read -r line || true; done
}

main "${@}"

