# config mapping
# ./foot                      -> ~/.config/foot
./alacritty                 -> ~/.config/alacritty
./fuzzel                    -> ~/.config/fuzzel
./hyprland                  -> ~/.config/hyprland
./i3                        -> ~/.config/i3
./kitty                     -> ~/.config/kitty
./niri                      -> ~/.config/niri
./qt6ct                     -> ~/.config/qt6ct
./qutebrowser/config.py     -> ~/.config/qutebrowser/config.py
./shell/bashrc              -> ~/.bashrc
./shell/shell_rc            -> ~/.shell_rc
./shell_programs            -> ~/.bin
./sway                      -> ~/.config/sway
./waybar                    -> ~/.config/waybar
./wofi                      -> ~/.config/wofi
./yazi                      -> ~/.config/yazi
./neovim/init.vim           -> /etc/xdg/nvim/init.vim
./vim/vimrc                 -> ~/.vimrc

