#!/usr/bin/env bash

set -euo pipefail

function log() {
    local type_="${1}"; shift 1
    printf '[%s]: %s' "${type_}" "${*}"
    [[ "${type_}" =~ (fatal|die|bail) ]] && exit 1
}

function ListNetworks() {
    sudo iw dev wlo1 scan | grep -P 'SSID:|^BSS' | sed -e 's/^[ \t]*SSID: //g' -e 's/^BSS \([0-9a-fA-F:]*\).*/\1/g' | paste -d' ' - -
}

function ConnetToNetwork() {
    local ssid="${1}"
    local psk="${2}"
    local tmp_file="${3}"
    wpa_passphrase "${ssid}" "${psk}" 1> "${tmp_file}"
    pgrep -f wpa_supplicant || log fatal "wpa_supplicant is already running"
    sudo wpa_supplicant -B -i "${iface}" -c "${tmp_file}"
}

function main() {
    local -a args=("${@}")
    local ssid pass iface tmp_file
    local -i should_connet=0

    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[$i]:-""}"
        case "${arg}" in
            list*)
                ListNetworks
                ;;
            conn*)
                ssid="${args[$((i+1))]:-""}"
                pass="${args[$((i+2))]:-""}"
                should_connet=1
                ;;
            ssid*=*|name*=*)
                ssid="${arg#*=}"
                ssid="${ssid:-""}"
                ;;
            pass*=*)
                pass="${arg#*=}"
                pass="${pass:-""}"
		;;
            -i=*)
                iface="${arg#*=}"
                iface="${iface:-""}"
                ;;
            -i*)
                iface="${args[$((i+1))]:-""}"
                ;;
            *)
                log fatal "Invalid arg: '${arg}'"
                ;;
        esac
    done

    if [[ "${should_connet}" -eq 1 ]]; then
        [[ -n "${ssid}" && -n "${pass}" ]] || log fatal "no enough arguments"
        if [[ -n "${ssid}" ]]; then
            [[ -n "${pass}" ]] || log fatal "no password given for ssid '${ssid}'"
        fi
        if [[ -n "${pass}" ]]; then
            [[ -n "${ssid}" ]] || log fatal "no ssid given for password '${ssid}'"
        fi
        tmp_file=$(mktemp -t wpa_supplicant.XXXX)
        trap 'rm -f ${tmp_file}' EXIT SIGINT SIGTERM
        ConnetToNetwork "${ssid}" "${pass}" "${tmp_file}" "${iface}"
    fi
}

main "${@}"

