#!/usr/bin/env bash

builtin set -euo pipefail

# ########## Output of this flag parser ##########
#
# $ bash argument_parser -flag1 flag1_value -flag2=flag2_value --flag3 flag3_value --flag4=flag4_value
# $  [info*]: flag1 var: 'flag1_value'
# $  [info*]: flag2 var: 'flag2_value'
# $  [info*]: flag3 var: 'flag3_value'
# $  [info*]: flag4 var: 'flag4_value'
# $  [warn^]: flag5 var (empty): ''
# $  [warn^]: flag6 var (empty): ''

declare NO_COLOR=0

# Logger
function log() {
    local _type="${1}"; shift
    local _color="" _t=""
    if [[ $NO_COLOR -eq 0 ]]; then
        local -g _info_color="\033[38;2;85;255;126m" \
            _warn_color="\033[38;2;255;170;10m" \
            _error_color="\033[38;2;244;29;31m" \
            _fatal_color="\033[5m\033[38;2;255;0;0m" \
            _other_color="\033[38;2;251;255;208m" \
            _nc="\033[0m"
    fi
    case "${_type}" in
        info) _color="${_info_color:-}" _t="*" ;;
        warn) _color="${_warn_color:-}" _t="^" ;;
        error) _color="${_error_color:-}" _t="!" ;;
        fatal) _color="${_fatal_color:-}" _t="#" ;;
        *) _color="${_other_color-""}" _t="" ;;
    esac

    printf "[%b%s%b%s]: %b\n" "${_color}" "${_type}" "${_nc}" "${_t}" "${*}"
}

# Flag parser
function parse_args() {
    local -n args=${1}

    local flag1_var="" flag2_var="" flag3_var=""
    local flag4_var="" flag5_var="" flag6_var=""

    local arg="" value=""
    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[i]}"
        [[ ( "$((${#args[@]} - i))" -ge 1 && -n "${args[$((i+1))]:-}" ) && \
            "${args[$((i+1))]:-}" != -* ]] && \
            value="${args[$((i+1))]:-}" i=$((i+1))
        if [[ "${arg}" == -*=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            [[ -n "${value}" ]] || \
                { log error "'${arg}' requires a value"; return 1; }
        fi
        case "${arg}" in
            --flag1) flag1_var="${value}" ;;
            --flag2) flag2_var="${value}" ;;
            --flag3) flag3_var="${value}" ;;
            --flag4) flag4_var="${value}" ;;
            --flag5) flag5_var="${value}" ;;
            --flag6) flag6_var="${value}" ;;
            *) log error "Invalid argument: '${arg}'" ;;
        esac
    done

    log_message() {
        local -n flag_var_ref=${1}
        local -i n=${2}
        flag_var_ref="${flag_var_ref:-}"
        { [[ -n "${flag_var_ref}" ]] && log info "flag${n} var: '${flag_var_ref}'"; } || \
            log warn "flag${n} var (empty): '${flag_var_ref}'"
    }

    log_message flag1_var 1
    log_message flag2_var 2
    log_message flag3_var 3
    log_message flag4_var 4
    log_message flag5_var 5
    log_message flag6_var 6

    unset -f log_message
}

# Main function
function main() {
    local -a arguments=("${@}")
    parse_args arguments
}

# Start from here
main "${@}"

